name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    name: "Ubuntu 22.04"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: ./.github/build.sh
      - name: Test
        shell: bash
        run: ./.github/test.sh
